/**
 * Session ID Helper
 * Provides utilities for managing stable connection IDs across the conversation
 */

import { randomUUID } from 'crypto';

/**
 * Session identifiers for a user connection
 */
export interface SessionIdentifiers {
    /** OpenAI's session ID (from realtime API) */
    openaiSessionId?: string;
    
    /** Custom connection ID (generated by us) */
    connectionId: string;
    
    /** User's phone number (once authenticated) */
    phoneNumber?: string;
    
    /** Timestamp when connection was created */
    createdAt: number;
}

/**
 * Get the best session key to use for storage
 * Priority: phone number > connection ID
 */
export function getSessionKey(identifiers: SessionIdentifiers): string {
    // Prefer phone number if available (user-specific)
    if (identifiers.phoneNumber) {
        return `phone_${identifiers.phoneNumber}`;
    }
    
    // Fall back to connection ID (connection-specific)
    return `conn_${identifiers.connectionId}`;
}

/**
 * Generate a new connection ID
 */
export function generateConnectionId(): string {
    return randomUUID();
}

/**
 * Extract session ID from agent context
 * This is what agents should call to get the session ID
 */
export function getSessionIdFromContext(context: any): string {
    // Try to get from context (passed from frontend)
    if (context?.sessionId) {
        return context.sessionId;
    }
    
    // Try connection ID
    if (context?.connectionId) {
        return context.connectionId;
    }
    
    // Try OpenAI session ID
    if (context?.openaiSessionId) {
        return context.openaiSessionId;
    }
    
    // Last resort: return 'unknown'
    console.warn('No session ID found in context, using "unknown"');
    return 'unknown';
}

/**
 * Create session identifiers from context
 */
export function createSessionIdentifiers(context: any): SessionIdentifiers {
    return {
        openaiSessionId: context?.openaiSessionId,
        connectionId: context?.connectionId || context?.sessionId || generateConnectionId(),
        phoneNumber: context?.phoneNumber,
        createdAt: Date.now(),
    };
}

/**
 * Update session identifiers with phone number after authentication
 */
export function updateSessionIdentifiersWithPhone(
    identifiers: SessionIdentifiers,
    phoneNumber: string
): SessionIdentifiers {
    return {
        ...identifiers,
        phoneNumber: phoneNumber,
    };
}

/**
 * Log session information for debugging
 */
export function logSessionInfo(identifiers: SessionIdentifiers, action: string): void {
    console.log(`[Session ${action}]`, {
        connectionId: identifiers.connectionId,
        phoneNumber: identifiers.phoneNumber || 'not authenticated',
        sessionKey: getSessionKey(identifiers),
        age: Math.floor((Date.now() - identifiers.createdAt) / 1000) + 's',
    });
}
